### PR TITLE
Added New Quotes in dataset.js

### PR DESCRIPTION
**Pull request by Aakriti-malla**

### CODE REVIEW

**Comment by Subham-Maity** [comment]
@Aakriti-malla Check This 
issue #96 

image

**Comment by Aakriti-malla** [comment]
Oh got it! will make the necessary changes right away!

**Comment by Aakriti-malla** [comment]
Hey! @Subham-Maity Check out the made Changes!

**Comment by Subham-Maity** [comment]
@Aakriti-malla Check Point no 2 -> All of them are perfect, but please add some meaning to each sentence like other contributors did

**Comment by Aakriti-malla** [comment]
Hey! I have added the meaning as well to the quotes. Check it out!

**Comment by Subham-Maity** [comment]
@Aakriti-malla **Thanks for perfectly placing emojis, explaining all the meanings, and specifying the person's names. I appreciate the effort you put into it.**

**Pull request merged**
