### PR TITLE
Changed script.js

### PR DESCRIPTION
**Pull request by Omm2005**

### CODE REVIEW

**Comment by Subham-Maity** [comment]
Sorry, @Omm2005 

- 1. **Make sure you open the project in an IDE such as Webstorm or VSCode so that you can understand the incorrectly typed data and key values. If I merge your code, the website will stop working.** 

- 2. **Take your time and learn this before you change it. If you watch carefully, you can easily understand** 

- 3. **Please use emojis as other contributes did.** 
- 4. correction - 
_line 4_ - First should be English, then add a tag like Hinglish, then add the Hinglish sentence. You can also see other sentences that are already there.
_line 5_ - Use normal Hindi not Sanskrit Gujarati Bengali etc 
_line 14_ - Something like storytelling is not allowed. Only those sentences that increase our stock of sentences 
_line 15_ - Same as line 5

You can check other's contributor's sentences and also you can check the `README.md` file  

image

**Comment by Subham-Maity** [comment]
@Omm2005 
**1. check your line 15 and add the appropriate meaning of it** 
**2. Add some appropriate emojis if possible** 

_all remains are fine_


image

**Comment by Subham-Maity** [comment]
@Omm2005 
check this. Use `:` instead of `=`

image

**Comment by Omm2005** [comment]
Done!

**Comment by Subham-Maity** [comment]
@Omm2005 Nice Work. Thanks! You put so much effort into this and I really appreciate it.

**Comment by Omm2005** [comment]
Thanks, Subham-Maity/StockOfSentence for taking me as a contributor to your
project. Also, I was a trouble for that I am sorry

**Pull request merged**
