### PR TITLE
Add 10 dialogues and quotes from Hollywood movies inside dataset #50

### PR DESCRIPTION
**Pull request by himalgnn**
I added 10 dialogues from hollywood movies with clear meaning inside dataset

### CODE REVIEW

**Comment by Subham-Maity** [comment]
@himalgnn **everything is fine but please include some appropriate emojis**

**Comment by himalgnn** [comment]
Done, added emojis too ! 🔥

**Comment by Subham-Maity** [comment]
@himalgnn hanks for placing perfectly emojis, explaining all the meanings, and specifying the name. I really appreciate the effort you put into it.

**Comment by himalgnn** [comment]
@Subham-Maity Most welcome 😊

**Pull request merged**
