### PR TITLE
added 5 quotes

### PR DESCRIPTION
**Pull request by amitkroutthedev**
added 5 quotes in document.js from line 1078 to line 1087

### CODE REVIEW

**Comment by Subham-Maity** [comment]
@amitkroutthedev **You made a lot of changes in the dataset, so sync your main branch then update and send a pull request again to resolve the conflict**

image

**Comment by amitkroutthedev** [comment]
Ok

**Comment by amitkroutthedev** [comment]
Please check the change

**Comment by Subham-Maity** [comment]
@amitkroutthedev **Read this** #96 

image

**Comment by amitkroutthedev** [comment]
oh ok I am adding quotes and re request.

**Pull request closed without merging**
