### PR TITLE
Added 20 quotes from Animes

### PR DESCRIPTION
**Pull request by swapn652**
PR for Issue #52

### CODE REVIEW

**Comment by Subham-Maity** [comment]
@swapn652 **You did a great job, but could you add some emojis?**

**Comment by swapn652** [comment]
@Subham-Maity I did add some emojis on few quotes but for the other quotes, I don't think any emoji would really fit in there. 
Like, for example if you take that quote: "Simplicity is the easiest path to true beauty.", what kind of emoji can you really add to this?

**Comment by Subham-Maity** [comment]
@swapn652 Simplicity is the easiest path to true beauty ☺️ <- You can use smiley faces or normal emojis

**Comment by swapn652** [comment]
@Subham-Maity Ok, thanks for the suggestion. I will do it now

**Comment by swapn652** [comment]
@Subham-Maity I did it. Please check.

**Pull request closed without merging**
