### PR TITLE
Added random sentence

### PR DESCRIPTION
**Pull request by VladenCode**

### CODE REVIEW

**Comment by Subham-Maity** [comment]
Hey @VladenCode ! It would be great if you could add more sentences, at least more than 5-6 sentences

**Comment by VladenCode** [comment]
Okay. Thank you! Will do tomorrow! :)

**Comment by VladenCode** [comment]
I added more sentences and pushed them to my branch.

**Comment by Subham-Maity** [comment]
@VladenCode Thanks for your contribution!

**Comment by VladenCode** [comment]
Thank you for the opportunity! Wish you a great day!

**Pull request merged**
