### PR TITLE
Added Quotes From one on my fav movies

### PR DESCRIPTION
**Pull request by workspace-utkarsh**
I have created this PR for hacktoberfest '22. I'm new to open source and looking for contributions on projects that interest me. Please consider my PR. Thankyou.

### CODE REVIEW

**Comment by Subham-Maity** [comment]
@workspace-utkarsh [Read this](https://github.com/Subham-Maity/StockOfSentence/issues/61#issue-1411208753)

**Comment by workspace-utkarsh** [comment]
> @workspace-utkarsh [Read this](https://github.com/Subham-Maity/StockOfSentence/issues/61#issue-1411208753)

Thankyou for the review. I'll make necessary changes and commit again.

**Comment by workspace-utkarsh** [comment]
I have made the necessary changes. Kindly review.

**Comment by workspace-utkarsh** [comment]
I have further modified my meanings. Hope this would be helpful. Thankyou.

**Comment by Subham-Maity** [comment]
@workspace-utkarsh Thanks !

**Pull request merged**
