### PR TITLE
Made intro container's display to flex

### PR DESCRIPTION
**Pull request by himalgnn**
I made the following improvements:- 
1. Intro container's display to flex and allign, justify-content to center
2. Edited intro container's paragraph from "Welcome to SOS World" to "Enter the SOS World" to make it more user friendly
Screenshot 2022-10-15 at 9 21 12 PM
Screenshot 2022-10-15 at 9 23 30 PM

### CODE REVIEW

**Comment by Subham-Maity** [comment]
@himalgnn **Great job**! Your effort on the project is greatly appreciated, and I **appreciate** what you have done.

**Comment by Subham-Maity** [comment]
@himalgnn It was working, but the random sentence function wasn't working, so I reverted, can you fix it?

**Comment by himalgnn** [comment]
> you

Did you mean to revert all the changes I've made ??
And what was working, could you please clarify more ?

**Comment by himalgnn** [comment]
@Subham-Maity Did you mean to revert all the changes I've made ??

**Comment by Subham-Maity** [comment]
@himalgnn Basically,  My main random function was not working properly after your changes, can you do the same thing with working conditions?

**Comment by himalgnn** [comment]
@Subham-Maity I've fixed it, please merge the pull request and see the changes !

**Comment by Subham-Maity** [comment]
@himalgnn Can you send me the pull request again ?

**Comment by himalgnn** [comment]
Please check again and merge !

**Comment by himalgnn** [comment]
@Subham-Maity Please check again and merge !

**Pull request merged**
