### PR TITLE
Added Popup to inform guests of audio-spacebar functionality

### PR DESCRIPTION
**Pull request by RXBlade**

### CODE REVIEW

**Comment by RXBlade** [comment]
I just read the other assignee's request and I can change it like that if you'd like, I thought this solution is looking better.

**Comment by Subham-Maity** [comment]
@RXBlade **That's cool but in order to make it more obvious, wouldn't it have been better to display this text on the main website and increase the size rather than a small text that looks more readable?**

**Comment by RXBlade** [comment]
@Subham-Maity hope you like it

**Comment by Subham-Maity** [comment]
@RXBlade **Thank you so much I appreciate the time and effort you put into it**

**Comment by Manoj0Marmat** [comment]
@RXBlade bruh you did same what i did

**Comment by RXBlade** [comment]
@Manoj0Marmat we were both assigned to this issue, I didn't copy your work if you're afraid of that. Check PR.

**Comment by Manoj0Marmat** [comment]
> @Manoj0Marmat we were both assigned to this issue, I didn't copy your work if you're afraid of that. Check PR.

@RXBlade are no bruh I mean ki you done with same concept I thought you have different approach for pop up

**Pull request merged**
