### PR TITLE
added new quotes in dataset.js

### PR DESCRIPTION
**Pull request by lishakothari**

### CODE REVIEW

**Comment by lishakothari** [comment]
@Subham-Maity please check :)

**Comment by Subham-Maity** [comment]
@lishakothari Please Check [**This**](https://github.com/Subham-Maity/StockOfSentence/issues/96)

**Comment by Subham-Maity** [comment]
@lishakothari 
**Check This** #96 
image

**Comment by lishakothari** [comment]
@Subham-Maity made the changes, please check! :)

**Comment by Subham-Maity** [comment]
@lishakothari  **no 2 point - like other contributors, you need to explain what the sentence means**

**Comment by lishakothari** [comment]
@Subham-Maity done! :)

**Comment by Subham-Maity** [comment]
@lishakothari Thanks for perfectly placing emojis, explaining all the meanings, and specifying the movie's names. I appreciate the effort you put into it.

**Pull request merged**
