### PR TITLE
Changed audio file to audio link

### PR DESCRIPTION
**Pull request by swapn652**
Closes Issue #86 

What I did is upload the already existing audio to a site, https://mailboxdrive.com/home/, which creates a link for an uploaded audio, and then replaced the source that had file name, by that link.

### CODE REVIEW

**Comment by Subham-Maity** [comment]
@swapn652 after exiting from the quote window and going back to the landing page, the audio does not end, and pause does not work with the spacebar

**Comment by swapn652** [comment]
@Subham-Maity take a look

**Comment by Subham-Maity** [comment]
@swapn652 Bugs: **Feature disabled**
-  **alert text appears when anyone pauses audio, but it isn't working in your branch**
<div>
Main Branch 

https://user-images.githubusercontent.com/97989643/197388537-91a688e9-510c-4a25-bbac-60ad39e215e0.mp4

Your Branch 


https://user-images.githubusercontent.com/97989643/197388545-472a82e2-21ef-4f2c-8e8a-a57aa915a740.mp4

</div>

**Comment by swapn652** [comment]
@Subham-Maity your site is working fine, according to your requirements. I think someone else has already worked on this issue. You can close this PR, without accepting my code.

**Comment by Subham-Maity** [comment]
@swapn652 I look forward to working together on this project or another in the future and I appreciate you taking the time to understand the project and spend your valuable time on it.

**Pull request closed without merging**
