### PR TITLE
Update dataset.js

### PR DESCRIPTION
**Pull request by baishu0105**
Added dialogues from 29-38

### CODE REVIEW

**Comment by Subham-Maity** [comment]
@baishu0105 Could you add a few appropriate emoji?

**Comment by baishu0105** [comment]
okok

**Comment by baishu0105** [comment]
done

**Comment by Subham-Maity** [comment]
@baishu0105 Thanks for placing perfectly emojis, explaining all the meanings, and specifying the person's name. I really appreciate the effort you put into it.

**Pull request merged**
