### PR TITLE
Text Show and Disappear Features

### PR DESCRIPTION
**Pull request by Manoj0Marmat**
Signed-off-by: Manoj Marmat <manojrajput762000@gmail.com>
Issue:
Adding new Feature #92 
Desc:
when user press space bar or click play button or click close button pop up gets disappear
otherwise pop up will show again
Screenshot:
Screen Recording 2022-10-21 at 11 34 49 PM

### CODE REVIEW

**Comment by Manoj0Marmat** [comment]
@Subham-Maity hey please review it

**Comment by Subham-Maity** [comment]
@Manoj0Marmat I really liked your design, and I appreciate the time and effort you put into it, but **would it be possible to change it a little bit so that the text disappears after 4-5 seconds even if someone is not pressing the spacebar, and when it pauses again, the text will appear and disappear after 4-5 seconds again?**  

and **would it be possible to slightly change the color to match the theme of our website?**

image

**Comment by Manoj0Marmat** [comment]
@Subham-Maity hey please review it 
Screen Recording 2022-10-22 at 8 43 41 AM

**Comment by Subham-Maity** [comment]
@Manoj0Marmat **The design is cool and I really liked the concept you created earlier. When someone pauses the music again, that message would appear, but two things need to be changed.**

#### Enhancement 
1. **The text should completely disappear even if someone is not pressing the spacebar after 2-3 sec (You can check the recent changes on the website a contributor changed this similar thing #93 )** 

- _note_ - **But he did not implement the excellent feature you implemented. Whenever someone pauses the audio, the text appears again,**
      
   -  but it should return to its normal state again after 2-3 seconds, which means that even if someone doesn't press the spacebar during that time, the text should again disappear completely like a loop.

#### Design 
2. **The text appears a little slow at the beginning. You can speed it up. and you also can decrease the radius** 

image


Note: **Please update the branch before making any changes otherwise there will be a conflict**

**Comment by Manoj0Marmat** [comment]
@Subham-Maity hey i've updated popup message feature please review it
Screen Recording 2022-10-22 at 11 34 20 PM 3

**Comment by Subham-Maity** [comment]
@Manoj0Marmat **Perfect! Your work is excellent, I really liked the design as well as the features you've implemented. It was great that you understood the project, identified the problem, and fixed it. Thank you so much.**

**Pull request merged**
