### PR TITLE
Change Play Button CSS

### PR DESCRIPTION
**Pull request by Nimesh-21**
I have increased the size of the button and the width of the playing and placed it on the top left of the box, so that it does not affect the content if placed inside the box.

### CODE REVIEW

**Comment by Subham-Maity** [comment]
@Nimesh-21 
**1. Place it on the right-down side inside the container** 
**2. There's a cut on the play button on the front, which should be fixed**

~ No issues with size. This is the perfect size 

image

**Comment by Nimesh-21** [comment]
> @Nimesh-21 **1. Place it on the right-down side inside the container** **2. There's a cut on the play button on the front, which should be fixed**
> 
> ~ No issues with size. This is the perfect size
> 
> image

Screenshot (20)
Is this fine now?

**Comment by Subham-Maity** [comment]
@Nimesh-21 can you sent another pull request

**Comment by Nimesh-21** [comment]
Sure

**Pull request closed without merging**
