### PR TITLE
Added 10 dialogues from money heist

### PR DESCRIPTION
**Pull request by deepesh85b**
#50 
@Subham-Maity 
you can merge it

### CODE REVIEW

**Comment by Subham-Maity** [comment]
@deepesh85b At least 10 sentences

**Comment by deepesh85b** [comment]
@Subham-Maity 
I have added 10..
You can merge it

**Comment by Subham-Maity** [comment]
@deepesh85b  
1. Correct the format 
2. Add emojis 
image

**Comment by deepesh85b** [comment]
> @deepesh85b
> 
>     1. Correct the format
> 
>     2. Add emojis
>        image

@Subham-Maity 
I have made changes

**Comment by Subham-Maity** [comment]
@deepesh85b **Thanks for perfectly placing emojis, explaining all the meanings, and specifying the person's name and the movie's name. I appreciate the effort you put into it.**

**Pull request merged**
