### PR TITLE
inspirational added again

### PR DESCRIPTION
**Pull request by JP109**
Added 12 inspirational quotes, most from Titanic, and made a new PR as requested. #103

### CODE REVIEW

**Comment by Subham-Maity** [comment]
@JP109 This is fine, but where is the meaning of those sentences and some of the dialogue is too long to add any meaning, so could you add some meaning and simplify this?

check this #96 
image

**Comment by JP109** [comment]
Okay, I'll edit them.

**Comment by JP109** [comment]
Added meanings to each dialogue, shortened or removed longer dialogues. Please check @Subham-Maity.

**Comment by Subham-Maity** [comment]
@JP109 **Thanks for perfectly placing emojis, explaining all the meanings, and specifying the movie's names. I appreciate the effort you put into it.**

**Pull request merged**
