### PR TITLE
Update dataset.js

### PR DESCRIPTION
**Pull request by FsocietyVoid**
Hi, I have added 10 Motivational quotes in the dataset.

### CODE REVIEW

**Comment by GeekyMax-Ytiam** [comment]
@FsocietyVoid 
### **1. Please Maintain the data format and check how everyone wrote the sentences**

image

### **2. Use emojis** 

#### Please Check the rules 👉 #121 @gregoris-io 

image

**Comment by FsocietyVoid** [comment]
Ok, Sorry for that , Now Can you check the the updated one?

**Review by Subham-Maity — APPROVED** [review]
conflict resolves

**Comment by Subham-Maity** [comment]
@FsocietyVoid **Thanks for perfectly placing emojis, explaining all the meanings, and specifying the movie's and character's names. I appreciate the effort you put into it.**

**Comment by FsocietyVoid** [comment]
My Pleasure !!! like to work on further projects too.

**Pull request merged**
