### PR TITLE
isuue#91 audio file removed and replaced with link

### PR DESCRIPTION
**Pull request by raghavpatidar**
The audio file was taken down, and a link to the audio file was replaced; it now functions flawlessly.

### CODE REVIEW

**Comment by Subham-Maity** [comment]
Hey @raghavpatidar thank you I appreciate your effort, but can you update the branch and then change what you changed some features were actually implemented related to audio, so your changes create a conflict.

**Comment by raghavpatidar** [comment]
Would you kindly clarify the modifications I need to do in order to update the branch? I established a new branch before creating a PR to ensure that the Main branch was unaffected.

**Comment by raghavpatidar** [comment]
Moreover, the webpage is accurate. After the upgrade, there are no new issues related to the audio.

**Comment by Subham-Maity** [comment]
@raghavpatidar #93 **Once you have checked this change, please sync your repo and update your code accordingly** 

image

**Comment by raghavpatidar** [comment]
I have resolved the conflict can you now accept my pull request.

**Comment by Subham-Maity** [comment]
@raghavpatidar **Thanks for your contribution**

**Pull request merged**
