### PR TITLE
Added 13 lines

### PR DESCRIPTION
**Pull request by Omm2005**
String line4 = "jo aatmaa ko maarane vaalaa samajhataa hai owr jo isako maraa samajhataa hai ve donon hii nahiin jaanate hain, kyonki yah aatmaa n marataa hai owr n maaraa jaataa hai.";
    String meaning4 = "He who thinks that the soul kills, and he who thinks of it as killed, are both ignorant. The soul kills not, nor is it killed.";
    row_increase++;

    String line5 = "nainam chhindanti shastraaṇi nainam dahati paavakah. n chainam kledayantyaapo n shoshayati maarutah॥ "
    String meaning5 = "Weapons do not cleave the soul, fire does not burn it, waters do not wet it, and wind does not dry it."
    row_increase++;

    String line6 = "Sometimes it is the people who no one imagines anything of who do the things that no one can imagine.";
    String meaning6 = "We should never underestimate people.";
    row_increase++;

    String line7 = "Strange, isn’t it? Each man’s life touches so many other lives. When he isn’t around he leaves an awful hole, doesn’t he?";
    String meaning7 = "no man is a failure who has friends.";
    row_increase++;

    String line8 = "There should be no boundaries to human endeavor. We are all different. However bad life may seem, there is always something you can do, and succeed at. While there’s life, there is hope.";
    String meaning8 = "Every Human is special";
    row_increase++;

    String line9 = "There is no God. No one directs the universe.";
    String meaning9 = "No one directs our fate";
    row_increase++;

    String line10 = "Hope is a dangerous thing. Hope can drive a man insane.";
    String meaning10 = "Every passing moment makes you failure when you hope and it never happens whatever you have hoped.";
    row_increase++;

    String line11 = "It's the possibility of having a dream come true that makes life interesting.";
    String meaning11 = "Without possibility, life is meaningless.";
    row_increase++;

    String line12 = "Remember, love that doesn't include honesty doesn't deserve to be called love.";
    String meaning12 = "There should be honesty within lovers or it isn't love.";
    row_increase++;

    String line13 = "Whether a man is a legend or not is decided by history, not fortune tellers.";
    String meaning13 = "A man is made legend by this karma and not by his Fate.";
    row_increase++;

    String line14 = "A man becomes a Mahadev, only when he fights for good. A Mahadev is not born from his mother's womb. He is forged in the heat of battle, when he wages a war to destroy evil. Har Har Mahadev - All of us are Mahadev.";
    String meaning14 = "A man become a legend when he fights for good. He fights hard for people's right. He is a leader.";
    row_increase++;

    String line15 = "aahaarastvapi sarvasy trividho bhavati priyah. yajñastapastathaa daanam teshaan bhedamimam shrṛṇu.";
    String meaning15 = "The food also which is dear to each is threefold, as also sacrifice, austerity and almsgiving. Hear thou the distinction of these.";
    row_increase++;

    String line16 = "A wise man can learn more from his enemies than a fool from his friends.";
    String meaning16 = "People who are foolish will never be able to benefit from the friends he or she has.";
    row_increase++;

### CODE REVIEW

**Comment by Subham-Maity** [comment]
@Omm2005 **It would be nice if you could change the Hindi to a combination of Hindi and English like Hinglish**

**Comment by Omm2005** [comment]
done!

**Comment by Omm2005** [comment]
@Subham-Maity Can you check if it is done correctly? I am new to GitHub so it's confusing, to be honest... so sorry for the trouble

**Comment by Subham-Maity** [comment]
Hey @Omm2005! 
- **Try to understand the project, how the code is written, and how functions are written on the website by adding all those lines in the JS file instead of the Java file**. 

Please read `README.md`

- **Note:** _The Java file is for those who don't understand how this website works (The basic idea of the project). It serves no purpose to our project._

**Comment by Omm2005** [comment]
ok i think i got it 
i made a new pull request

**Pull request closed without merging**
